# Name of the workflow
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request events
on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Run the build first
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'

    # Install Nerdbank.GitVersioning
    - name: install nbgv
      run: dotnet tool install --tool-path . nbgv

    # Set version
    - name: set version
      run: ./nbgv cloud

    # Build command line tool
    - name: dotnet build
      run: dotnet build -c Release
      working-directory: src/BuildDacpac/

    # Run tests for command line tool
    - name: dotnet test
      run: dotnet test -c Release
      working-directory: test/BuildDacpac.Tests/

    # Run build for SDK package
    - name: dotnet build
      run: dotnet build -c Release
      working-directory: src/MSBuild.Sdk.SqlProj

    # Ensure that test project builds
    - name: dotnet build TestProject
      run: dotnet build -c Release
      working-directory: test/TestProject
    
    # Package
    - name: dotnet pack
      run: dotnet pack -c Release src/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj.csproj

    # Upload package
    - name: upload
      uses: actions/upload-artifact@v1
      with:
        name: nuget-package
        path: ./src/MSBuild.Sdk.SqlProj/bin/Release/

  # Run tests in parallel
  test:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ "ubuntu-18.04", "macos-10.15", "windows-2019" ]
        dotnet: [ '2.1.804', '3.1.102' ]
        include:
          - os: ubuntu-18.04
            sqlpackage-url: "https://go.microsoft.com/fwlink/?linkid=2113331"
          - os: macos-10.15
            sqlpackage-url: "https://go.microsoft.com/fwlink/?linkid=2113705"
          - os: windows-2019
            sqlpackage-url: "https://go.microsoft.com/fwlink/?linkid=2113704"
      fail-fast: false

    steps:
    # Fetch sources
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
 
    # Setup .NET SDK
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    # Apply Nerdbank.GitVersioning
    - uses: aarnott/nbgv@v0.3
      id: nbgv

    # Replace tokens 
    - uses: cschleiden/replace-tokens@v1
      name: replace tokens
      with:
        files: 'test/TestProjectWithSDKRef/TestProjectWithSDKRef.csproj'
      env:
        VERSION: ${{ steps.nbgv.outputs.NuGetPackageVersion }}

    # Download artifact
    - name: download-artifact
      uses: actions/download-artifact@v1
      with:
        name: nuget-package
        path: test/TestProjectWithSDKRef/nuget-package

    # Restore packages
    - name: dotnet restore
      run: dotnet restore --verbosity n
      working-directory: ./test/TestProjectWithSDKRef/

    # Build the project
    - name: build project
      run: dotnet build
      working-directory: ./test/TestProjectWithSDKRef/

    # Upload artifact
    - name: upload
      uses: actions/upload-artifact@v1
      with:
        name: dacpac-package
        path: ./test/TestProjectWithSDKRef/bin/Debug/netstandard2.0/

  # Attempt to deploy the resulting dacpac's to a SQL Server instance running in a container
  deploy:
    runs-on: ubuntu-18.04
    needs: test
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: temp-container-password
        ports:
          - 1433:1433
    steps:
    # Download artifacts
    - name: download-artifact
      uses: actions/download-artifact@v1
      with:
        name: dacpac-package
        path: ~/dacpac-package

    # Download sqlpackage
    - name: download sqlpackage
      run: >
        curl -L https://go.microsoft.com/fwlink/?linkid=2113331 --output sqlpackage.zip &&
        unzip sqlpackage.zip -d ~/sqlpackage &&
        chmod a+x ~/sqlpackage/sqlpackage

    # Run sqlpackage
    - name: sqlpackage publish
      run: >
        ~/sqlpackage/sqlpackage
        /Action:Publish
        /SourceFile:~/dacpac-package/TestProjectWithSDKRef.dacpac
        /TargetServerName:localhost
        /TargetUser:sa
        /TargetPassword:temp-container-password
        /TargetDatabaseName:TestProjectWithSDKRef

    # Dump logs of the container if something failed
    - name: Dump docker logs on failure
      if: failure()
      uses: jwalton/gh-docker-logs@v1

  # Publish the NuGet package to NuGet.org
  publish:
    runs-on: ubuntu-18.04
    needs: deploy
    steps:
    # Setup .NET SDK
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'

    # Download artifacts
    - name: download-artifact
      uses: actions/download-artifact@v1
      with:
        name: nuget-package
        path: ~/nuget-package

    # Push
    - name: dotnet nuget push
      run: dotnet nuget push ~/nuget-package/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json